### ISSUE TITLE
the jgiven html5 report tries to read all *.json files

### ISSUE THREAD

**Issue by adrian-herscu** [TNG/JGiven#107]
Given any.json file in any subfolder
and any.json files contents are:
{{}} // that's illegal
When the HTML5 reporter runs
Then the following exception is thrown:

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonExcepti
on: Expected name at line 1 column 2 path $.
	at com.google.gson.Gson.fromJson(Gson.java:820)
	at com.google.gson.Gson.fromJson(Gson.java:743)
	at com.tngtech.jgiven.report.json.ScenarioJsonReader.apply(ScenarioJsonReader.j
ava:20)
	at com.tngtech.jgiven.report.json.ReportModelFileReader.apply(ReportModelFileRe
ader.java:13)
	at com.tngtech.jgiven.report.json.ReportModelFileReader.apply(ReportModelFileRe
ader.java:8)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:
48)
	at com.tngtech.jgiven.report.json.JsonModelTraverser.traverseModels(JsonModelTr
averser.java:19)
	at com.tngtech.jgiven.report.json.ReportModelReader.readDirectory(ReportModelRe
ader.java:17)
	at com.tngtech.jgiven.report.ReportGenerator.generate(ReportGenerator.java:96)
	at com.ebay.cpa.sema4ci.testing.Launcher.main(Launcher.java:55)
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 
1 column 2 path $.
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1572)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:515)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:416)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Refl
ectiveTypeAdapterFactory.java:177)
	at com.google.gson.Gson.fromJson(Gson.java:805)
	... 10 more

**Comment by janschaefer** [comment]
How do you execute the reporter, with the maven plugin or standalone? Do you specify the source directory using the --sourceDir option?

**Comment by adrian-herscu** [comment]
try {
            final ReportGenerator generator = new ReportGenerator();
            // TODO make these parameters configurable -- once the Launcher will
            // become Configurable
            generator.setTargetDirectory(new File("reports"));
            generator.setFormat(Format.HTML5);
            generator.generate();
        } catch (final Exception e) {
            e.printStackTrace();
        }

**Comment by janschaefer** [comment]
Do you have any updates on this issue?

**Comment by janschaefer** [comment]
I close this issue for now. Please reopen if it isn't solved for you.
