### ISSUE TITLE
java.lang.IncompatibleClassChangeError in ValueInjector while getting ScenarioStateFields 

### ISSUE THREAD

**Issue by mjellat** [TNG/JGiven#1082]
Hi all,

I'm getting a IncompatibleClassChangeError when executing my Test with a ScenarioState object 

```
java.lang.IncompatibleClassChangeError: Class com.tngtech.jgiven.impl.inject.ScenarioStateField$1 does not implement the requested interface java.util.function.Function

	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.tngtech.jgiven.impl.inject.ValueInjector.getScenarioFields(ValueInjector.java:73)
	at com.tngtech.jgiven.impl.inject.ValueInjector.validateFields(ValueInjector.java:45)
	at com.tngtech.jgiven.impl.inject.ValueInjector.updateValues(ValueInjector.java:102)
	at com.tngtech.jgiven.impl.ScenarioExecutor.updateScenarioState(ScenarioExecutor.java:239)
	at com.tngtech.jgiven.impl.ScenarioExecutor.access$500(ScenarioExecutor.java:41)
	at com.tngtech.jgiven.impl.ScenarioExecutor$StageTransitionHandlerImpl.enterStage(ScenarioExecutor.java:172)
	at com.tngtech.jgiven.impl.intercept.StepInterceptorImpl.intercept(StepInterceptorImpl.java:80)
	at com.tngtech.jgiven.impl.intercept.ByteBuddyMethodInterceptor.interceptSuper(ByteBuddyMethodInterceptor.java:37)
```

I'm using the version 1.2.4 with java17 and spring.

After some research I found, that in the `ValueInjector` open up a jdk stream of the scenariofields expecting a `java.util.Function` in a map call. But the `ScenarioStateField.fromField` returns a `com.google.common.base.Function`

https://github.com/TNG/JGiven/blob/9a59242107ccfd92364b161503e049d062bb0f29/jgiven-core/src/main/java/com/tngtech/jgiven/impl/inject/ValueInjector.java#L72

Am I doing something wrong??

thx

**Comment by mjellat** [comment]
After more research, it's a dependency problem... Sorry for this issue
