### ISSUE TITLE
Streamline stacktrace in case of errors

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#112]
Hi there,

some other feedback from our developers that is worth sharing with you.

In comparison to a JGiven based test to a non JGiven based test, the stack trace is inflated due to the proxy interception. Example:

```
java.lang.IllegalStateException: Existance mismatch for 'supplierAudits{expiryDate,completionDate}': expected true, but was false
	at org.springframework.util.Assert.state(Assert.java:385)
	at com.sobis.jaf.tests.jgiven.JsonTestStage.fields_$_exist_$(JsonTestStage.java:85)
	at com.sobis.suma.tests.SumaJsonCreatorFieldTests$SumaJsonTestSteps$$EnhancerByCGLIB$$ef573a45.CGLIB$fields_$_exist_$$4(<generated>)
	at com.sobis.suma.tests.SumaJsonCreatorFieldTests$SumaJsonTestSteps$$EnhancerByCGLIB$$ef573a45$$FastClassByCGLIB$$17d90daa.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at com.tngtech.jgiven.impl.intercept.StandaloneStepMethodInterceptor$1.proceed(StandaloneStepMethodInterceptor.java:26)
	at com.tngtech.jgiven.impl.intercept.StepMethodInterceptor.doIntercept(StepMethodInterceptor.java:59)
	at com.tngtech.jgiven.impl.intercept.StandaloneStepMethodInterceptor.intercept(StandaloneStepMethodInterceptor.java:30)
	at com.sobis.suma.tests.SumaJsonCreatorFieldTests$SumaJsonTestSteps$$EnhancerByCGLIB$$ef573a45.fields_$_exist_$(<generated>)
	at com.sobis.suma.tests.SumaJsonCreatorFieldTests.render_read_and_edit_mode_fields(SumaJsonCreatorFieldTests.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at com.tngtech.java.junit.dataprovider.DataProviderFrameworkMethod.invokeExplosively(DataProviderFrameworkMethod.java:77)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at com.tngtech.jgiven.junit.ScenarioExecutionRule$1.evaluate(ScenarioExecutionRule.java:74)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at com.sobis.jaf.tests.spring.ApplicationJUnit4ClassRunner$1.evaluate(ApplicationJUnit4ClassRunner.java:283)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

This trace is not as easy to read as before and it contains many proxy/interception lines between the code that is actually invoked in the test. Do you see any way in streamlining the stacktrace that is provided, e.g.?

```
java.lang.IllegalStateException: Existance mismatch for 'supplierAudits{expiryDate,completionDate}': expected true, but was false
	at org.springframework.util.Assert.state(Assert.java:385)
	at com.sobis.jaf.tests.jgiven.JsonTestStage.fields_$_exist_$(JsonTestStage.java:85)
	at com.sobis.suma.tests.SumaJsonCreatorFieldTests.render_read_and_edit_mode_fields(SumaJsonCreatorFieldTests.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at com.tngtech.java.junit.dataprovider.DataProviderFrameworkMethod.invokeExplosively(DataProviderFrameworkMethod.java:77)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at com.tngtech.jgiven.junit.ScenarioExecutionRule$1.evaluate(ScenarioExecutionRule.java:74)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at com.sobis.jaf.tests.spring.ApplicationJUnit4ClassRunner$1.evaluate(ApplicationJUnit4ClassRunner.java:283)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

It makes JGiven even more transparent, improves the readability and allows a developer to better focus about what is going wrong.

Best regards,
Niko

**Comment by janschaefer** [comment]
You could even strip it further down by using the following Eclipse JUnit stacktrace filter preferences:
![junitstacktracefilter](https://cloud.githubusercontent.com/assets/3749345/9635581/70a10cee-5197-11e5-8949-63eb0f272980.png)

The resulting stacktrace would look something like this (note that you have to enable the 'Filter Stacktrace' option in the JUnit stacktrace view):

```
java.lang.IllegalStateException: Existance mismatch for 'supplierAudits{expiryDate,completionDate}': expected true, but was false
    at org.springframework.util.Assert.state(Assert.java:385)
    at com.sobis.jaf.tests.jgiven.JsonTestStage.fields_$_exist_$(JsonTestStage.java:85)
    at com.sobis.suma.tests.SumaJsonCreatorFieldTests.render_read_and_edit_mode_fields(SumaJsonCreatorFieldTests.java:63)
    at com.tngtech.java.junit.dataprovider.DataProviderFrameworkMethod.invokeExplosively(DataProviderFrameworkMethod.java:77)
    at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
    at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
    at com.tngtech.jgiven.junit.ScenarioExecutionRule$1.evaluate(ScenarioExecutionRule.java:74)
    at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
    at com.sobis.jaf.tests.spring.ApplicationJUnit4ClassRunner$1.evaluate(ApplicationJUnit4ClassRunner.java:283)
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
```

**Comment by janschaefer** [comment]
With additional preferences you can even remove the springframework stuff.

**Comment by nikowitt** [comment]
I see... my bad, even after years of using Eclipse, I haven't discovered everything :) Thank you very much!

Yes, I know that this is unrelated to the original request, but since you seem to be an Eclipse expert, do you know if there is any possibility to add the -parameters flag to the built-in compiler?

**Comment by janschaefer** [comment]
Actually, the -parameters flag will not be necessary anymore with the upcoming v0.8.1 release, which I hope to release within the next days. However, in the meantime you can configure Eclipse accordingly by opening your project settings and configure the Java Compiler:

![eclipseparameterssettings](https://cloud.githubusercontent.com/assets/3749345/9651101/29716c72-520c-11e5-9d72-d9e324337164.png)

**Comment by nikowitt** [comment]
Now I know why I haven't found this - the checkbox is disabled unless the compiler compliance level is not set to 1.8.

Thanks for the hint!
