### ISSUE TITLE
Unable to use CaseDescription when param contains reserved regexp character

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#177]
Hi Jan,

```
	@Test
	@DataProvider(splitBy = __, value = {
			"Test/Project # Name " + __ + "Test Project Name",
			"\r\nTest/  %Project% # Name *" + __ + "Test Project Name",
			"Test Project Name in C$ash" + __ + "Test Project Name"
	})
	@CaseDescription("Input '$0'")
	public void strip_invalid_imap_folder_name_characters(String input, String output) throws Exception {
		assert_that().assert_expression(JAFStringUtils.stripInvalidIMAPFolderNameCharacters(input), is(output),
				"via 'stripInvalidIMAPFolderNameCharacters(String name)'");
	}
```

returns an error:
```
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Unknown Source)
	at com.tngtech.jgiven.impl.params.DefaultCaseDescriptionProvider.description(DefaultCaseDescriptionProvider.java:42)
	at com.tngtech.jgiven.impl.ScenarioModelBuilder.setCaseDescription(ScenarioModelBuilder.java:306)
	at com.tngtech.jgiven.impl.ScenarioModelBuilder.scenarioStarted(ScenarioModelBuilder.java:292)
	at com.tngtech.jgiven.impl.StandaloneScenarioExecutor.startScenario(StandaloneScenarioExecutor.java:440)
	at com.tngtech.jgiven.impl.ScenarioBase.startScenario(ScenarioBase.java:75)
	at com.tngtech.jgiven.junit.ScenarioExecutionRule.starting(ScenarioExecutionRule.java:110)
	at com.tngtech.jgiven.junit.ScenarioExecutionRule$1.evaluate(ScenarioExecutionRule.java:72)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
```

So an additional escape for params is required.

**Comment by janschaefer** [comment]
Ah, this is a classic. I fall into this trap already. I forgot to call quoteReplacement on the argument.

**Comment by nikowitt** [comment]
Hehe, so did I :)

**Comment by janschaefer** [comment]
This is an ideal use case to try out property based testing :-)
