### ISSUE TITLE
JGiven integration tests fails when run with maven parallel build

### ISSUE THREAD

**Issue by swapsmagic** [TNG/JGiven#192]
Jgiven integration test fails with below exception when run with mvn -T 1C (parallel build)

`java.lang.NullPointerException: null
	at com.tngtech.jgiven.impl.StandaloneScenarioExecutor.invokeRuleMethod(StandaloneScenarioExecutor.java:278)
	at com.tngtech.jgiven.impl.StandaloneScenarioExecutor.ensureBeforeStepsAreExecuted(StandaloneScenarioExecutor.java:233)
	at com.tngtech.jgiven.impl.StandaloneScenarioExecutor.update(StandaloneScenarioExecutor.java:193)
	at com.tngtech.jgiven.impl.StandaloneScenarioExecutor.access$100(StandaloneScenarioExecutor.java:45)
	at com.tngtech.jgiven.impl.StandaloneScenarioExecutor$MethodHandler.handleMethod(StandaloneScenarioExecutor.java:120)
	at com.tngtech.jgiven.impl.intercept.StepMethodInterceptor.intercept(StepMethodInterceptor.java:80)
	at com.tngtech.jgiven.impl.intercept.StepMethodInterceptor.doIntercept(StepMethodInterceptor.java:61)
	at com.tngtech.jgiven.impl.intercept.StandaloneStepMethodInterceptor.intercept(StandaloneStepMethodInterceptor.java:30)`

This works well when run in a single thread (without parallel option)

**Comment by swapsmagic** [comment]
Tests are written using JUnit.

**Comment by swapsmagic** [comment]
Version used: 0.9.1

**Comment by swapsmagic** [comment]
Just an update:
- I see the same error when building the packages in parallel mode and running integration tests in non parallel mode.

**Comment by janschaefer** [comment]
I tried to reproduce the problem, but was not able to do so. I also cannot see how it is possible to have a NPE in line 278 of StandaloneScenarioExecutor (in v0.9.1). Could you please upgrade JGiven to v0.11.2 and tell me the result?

**Comment by janschaefer** [comment]
Do you have any updates on this issue?

**Comment by swapsmagic** [comment]
Haven't had chance to investigate it further. You can go ahead and close it for now and i can reopen once i get back to it. Thanks for looking into it though.

**Comment by janschaefer** [comment]
I close this issue now. If you have any updates, please feel to reopen it.
