### ISSUE TITLE
./gradlew build leads to failure

### ISSUE THREAD

**Issue by rolfschumacher** [TNG/JGiven#223]
on Debian Linux. I am trying this the first time, hence, not sure whether it is my fault.
Shouldn't it build smoothly?
The failure is:
:jgiven-html5-report:bowerUpdate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jgiven-html5-report:bowerUpdate'.
> A problem occurred starting process 'command 'bower''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Regards

Rolf

Stacktrace:
`
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jgiven-html5-report:bowerUpdate'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
  ...
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'bower''
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:196)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:325)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:83)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'bower'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:65)
	... 2 more
Caused by: java.io.IOException: Cannot run program "bower" (in directory "/home/rsc/workspace/JGiven/jgiven-html5-report"): error=2, No such file or directory
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 4 more
Caused by: java.io.IOException: error=2, No such file or directory
	... 5 more

BUILD FAILED`

**Comment by janschaefer** [comment]
You need to have bower installed. The requirements for building JGiven are explained in [CONTRIBUTING.md](https://github.com/TNG/JGiven/blob/master/CONTRIBUTING.md)
