### ISSUE TITLE
Error while running gradle task jgivenReport

### ISSUE THREAD

**Issue by RoRoche** [TNG/JGiven#253]
[Here is the Android project where I'm using JGiven](https://github.com/RoRoche/AndroidTestingBox).

I wrote [a simple test class with JGiven](https://github.com/RoRoche/AndroidTestingBox/blob/master/AndroidTestingBox/app/src/test/java/com/guddy/android_testing_box/JGivenSumTest.java).

When running the gradle task `gradle jgivenReport`, declared such as:

```
task jgivenReport(type: JavaExec, dependsOn: 'test') {
    main = 'com.tngtech.jgiven.report.ReportGenerator'
    args '--targetDir=target/jgiven-reports/html',
            '--format=html'
    classpath = configurations.testCompile
}
```

I get the following error:

```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
        at com.google.gson.Gson.fromJson(Gson.java:887)
        at com.google.gson.Gson.fromJson(Gson.java:825)
        at com.tngtech.jgiven.report.json.ScenarioJsonReader.apply(ScenarioJsonReader.java:20)
        at com.tngtech.jgiven.report.json.ReportModelFileReader.apply(ReportModelFileReader.java:13)
        at com.tngtech.jgiven.report.json.ReportModelFileReader.apply(ReportModelFileReader.java:8)
        at com.google.common.collect.Iterators$8.transform(Iterators.java:817)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.tngtech.jgiven.report.json.JsonModelTraverser.traverseModels(JsonModelTraverser.java:19)
        at com.tngtech.jgiven.report.json.ReportModelReader.readDirectory(ReportModelReader.java:23)
        at com.tngtech.jgiven.report.ReportGenerator.readReportModel(ReportGenerator.java:158)
        at com.tngtech.jgiven.report.ReportGenerator.generate(ReportGenerator.java:145)
        at com.tngtech.jgiven.report.ReportGenerator.main(ReportGenerator.java:96)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
        ... 12 more
:app:jgivenReport FAILED
```

Here is the [generated JSON report](https://github.com/RoRoche/AndroidTestingBox/blob/master/AndroidTestingBox/app/jgiven-reports/com.guddy.android_testing_box.JGivenSumTest.json), which is valid according to online JSON validator tools.

**Comment by janschaefer** [comment]
Most likely the report generator read a non-JGiven JSON file. As you have not specified the `--sourceDir`, the report generator takes `.` as the source folder and searches recursively for json files.

**Comment by RoRoche** [comment]
Absolutely right! Thanks a lot.

**Comment by janschaefer** [comment]
I will update the documentation for gradle accordingly as in most cases you should specify the sourceDir. In addition JGiven could handle that error more gracefully.

**Comment by wolfs** [comment]
@janschaefer You could also document the now existing Gradle plugin ;)

**Comment by janschaefer** [comment]
Yes, definitely. I hope to publish that soon.
