### ISSUE TITLE
A step annotated @Pending raises NoSuchMethodError exception at runtime

### ISSUE THREAD

**Issue by dgrandemange** [TNG/JGiven#278]
When marking a step pending (`@Pending` annotation on stage method), a `NoSuchMethodError` exception is raised while executing the tests.
After removing the annotation, no exception is raised.

Components version :
- jgiven components (core, junit, html5-report, spring) version : 0.13.0,
- jgiven-core transitive dependency jansi version is  1.13

Full stackTrace :
`java.lang.NoSuchMethodError: org.fusesource.jansi.Ansi.fgBright(Lorg/fusesource/jansi/Ansi$Color;)Lorg/fusesource/jansi/Ansi;
	at com.tngtech.jgiven.report.text.PlainTextWriter.withColor(PlainTextWriter.java:57)
	at com.tngtech.jgiven.report.text.PlainTextWriter.gray(PlainTextWriter.java:29)
	at com.tngtech.jgiven.report.text.PlainTextScenarioWriter.printStep(PlainTextScenarioWriter.java:120)
	at com.tngtech.jgiven.report.text.PlainTextScenarioWriter.visit(PlainTextScenarioWriter.java:93)
	at com.tngtech.jgiven.report.model.StepModel.accept(StepModel.java:77)
	at com.tngtech.jgiven.report.model.ScenarioCaseModel.accept(ScenarioCaseModel.java:73)
	at com.tngtech.jgiven.report.model.ScenarioModel.accept(ScenarioModel.java:28)
	at com.tngtech.jgiven.report.text.PlainTextReporter.visit(PlainTextReporter.java:68)
	at com.tngtech.jgiven.report.model.ScenarioModel.accept(ScenarioModel.java:26)
	at com.tngtech.jgiven.report.model.ReportModel.accept(ReportModel.java:45)
	at com.tngtech.jgiven.report.text.PlainTextReporter.write(PlainTextReporter.java:51)
	at com.tngtech.jgiven.report.impl.CommonReportHelper.finishReport(CommonReportHelper.java:30)
	at com.tngtech.jgiven.junit.ScenarioReportRule.finished(ScenarioReportRule.java:11)
	at org.junit.rules.TestWatcher.finishedQuietly(TestWatcher.java:117)
	at org.junit.rules.TestWatcher.access$400(TestWatcher.java:46)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:64)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)`

**Comment by janschaefer** [comment]
The only explanation I have for is that there is some other Jansi version somewhere in your classpath. Could you double check that?

**Comment by janschaefer** [comment]
The method `fgBright` was introduced in version 1.9 of Jansi, so I guess you must have some older version in your classpath

**Comment by dgrandemange** [comment]
Well, a maven dependency:tree only shows a jansi 1.13 in the dependencies tree.

Now, it seems you were right. 
As i am actually trying to migrate an existing JBehave/Serenity project to JGiven, there were still JBehave/Serenity plugins sections remaining in my pom.xml. 
Once removed, the jAnsi issue does not occur anymore.
Maybe one of the removed dep was an uber Jar embedding an older version of jAnsi...
Anyway, works fine now.
Thank you.

**Comment by janschaefer** [comment]
Ok. Perfect. Thanks for verifying!
