### ISSUE TITLE
Mockito compatibility issue 

### ISSUE THREAD

**Issue by Dossea** [TNG/JGiven#309]
I'm (at the moment of typing) using the latest version of Mockito-core (2.7.19) which depends on byte-buddy version 1.6.11 (https://mvnrepository.com/artifact/org.mockito/mockito-core/2.7.19).

This makes it unable to use it in combination with the latest version of jGiven (currently 0.14.1) since it uses byte-buddy version 1.5.1.

With that setup I get the following error:
```
java.lang.NoSuchMethodError: net.bytebuddy.implementation.MethodDelegation.appendParameterBinder(Lnet/bytebuddy/implementation/bind/annotation/TargetMethodAnnotationDrivenBinder$ParameterBinder;)Lnet/bytebuddy/imp
        at com.tngtech.jgiven.impl.ByteBuddyStageClassCreator.createStageClass(ByteBuddyStageClassCreator.java:45)
        at com.tngtech.jgiven.impl.CachingStageClassCreator.getCachedClass(CachingStageClassCreator.java:29)
        at com.tngtech.jgiven.impl.CachingStageClassCreator.createStageClass(CachingStageClassCreator.java:22)
        at com.tngtech.jgiven.impl.DefaultStageCreator.createStage(DefaultStageCreator.java:18)
        at com.tngtech.jgiven.impl.ScenarioExecutor.addStage(ScenarioExecutor.java:203)
        at com.tngtech.jgiven.impl.Scenario.initialize(Scenario.java:98)
        at com.tngtech.jgiven.impl.ScenarioBase.performInitialization(ScenarioBase.java:91)
        at com.tngtech.jgiven.impl.ScenarioBase.startScenario(ScenarioBase.java:74)
        at com.tngtech.jgiven.junit.JGivenMethodRule.starting(JGivenMethodRule.java:109)
        at com.tngtech.jgiven.junit.JGivenMethodRule$1.evaluate(JGivenMethodRule.java:71)
```

I solved this issue by downgrading Mockito-core to version 2.5.2 (the last version of Mockito that uses byte-buddy 1.5.x)

I don't know if you have a specific reason for not using the latest version of byte-buddy, so please note that this post is only informative for others that may have the same issue.

**Comment by janschaefer** [comment]
Ok. Thanks for the info. I will upgrade the byte buddy version with the next release.

**Comment by janschaefer** [comment]
It is still a bit surprising that ByteBuddy introduces a backwards-incompatible API change in a minor version upgrade.
