### ISSUE TITLE
Update ByteBuddy version (or shade it) to be compatible with other libs

### ISSUE THREAD

**Issue by heldev** [TNG/JGiven#314]
Hi, I was looking forward to trying JGiven in a real project, but unfortunately my try has failed. Due to the [ButeBuddy known backward compatibility issues](https://github.com/mockito/mockito/issues/943)  it's impossible to use JGiven with the new versions of other libs (e.g mockito
uses net.bytebuddy:byte-buddy:jar:1.6.11 ) because you'll get the exception:
`ERROR!
java.lang.NoSuchMethodError: net.bytebuddy.implementation.MethodDelegation.appendParameterBinder(Lnet/bytebuddy/implementation/bind/annotation/TargetMethodAnnotationDrivenBinder$ParameterBinder;)Lnet/bytebuddy/implementation/MethodDelegation;
        at com.tngtech.jgiven.impl.ByteBuddyStageClassCreator.createStageClass(ByteBuddyStageClassCreator.java:45)
        at com.tngtech.jgiven.impl.CachingStageClassCreator.getCachedClass(CachingStageClassCreator.java:29)
        at com.tngtech.jgiven.impl.CachingStageClassCreator.createStageClass(CachingStageClassCreator.java:22)
        at com.tngtech.jgiven.impl.DefaultStageCreator.createStage(DefaultStageCreator.java:18)
        at com.tngtech.jgiven.impl.ScenarioExecutor.addStage(ScenarioExecutor.java:203)
        at com.tngtech.jgiven.impl.Scenario.initialize(Scenario.java:98)
        at com.tngtech.jgiven.impl.ScenarioBase.performInitialization(ScenarioBase.java:91)
        at com.tngtech.jgiven.impl.ScenarioBase.startScenario(ScenarioBase.java:74)
        at com.tngtech.jgiven.junit.JGivenMethodRule.starting(JGivenMethodRule.java:109)
        at com.tngtech.jgiven.junit.JGivenMethodRule$1.evaluate(JGivenMethodRule.java:71)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
`

I also saw #310 in the backlog of the v0.16.0 milestone but it seems a bit too far because it basically blocks users from adopting the library. Would it be possible to prioritize that issue or apply some temporary fix (like a version update or a 'shading') ?

**Comment by heldev** [comment]
Sorry, I dint noticed your latest release notes.

**Comment by janschaefer** [comment]
No Problem, the release was just done yesterday :-). Let us know if there are any issues that prevents you from using JGiven in your project. We are always happy for feedback!
