### ISSUE TITLE
@Table annotation causes Nullpointer exception

### ISSUE THREAD

**Issue by jackblack81** [TNG/JGiven#416]
Is passing NULL to  @Table  annotated parameter supposed to throw NullpointerException?
That's really inconvenient for reusing that step method.

Steps to reproduce:

```
 given().something()
 .and().some_other_stuff(null);
  when().something_is_called();
 then().result_should_contain(1);
```
Then in stage Class:

```
   public StageClass some_other_stuff(@Table List<Entity> entities) {
       ....
    }
```

I get following stack trace:

```
java.lang.NullPointerException
	at com.tngtech.jgiven.format.table.DefaultTableFormatter.toIterable(DefaultTableFormatter.java:190)
	at com.tngtech.jgiven.format.table.DefaultTableFormatter.toDataTable(DefaultTableFormatter.java:98)
	at com.tngtech.jgiven.format.table.DefaultTableFormatter.format(DefaultTableFormatter.java:36)
	at com.tngtech.jgiven.report.model.StepFormatter$TableFormatting.formatTable(StepFormatter.java:99)
	at com.tngtech.jgiven.report.model.StepFormatter.getRemainingArguments(StepFormatter.java:340)

```

**Comment by janschaefer** [comment]
I suggest you should create a separate method without any parameters and give it a meaningful name. You could still reuse common code by extracting common code to another internal method. I think throwing an NPE is correct here to fail fast. I would rather not change that behavior.
