### ISSUE TITLE
Gradle internal API changed

### ISSUE THREAD

**Issue by sharedprophet** [TNG/JGiven#437]
Please remove references to the Gradle internal API. They are causing errors on newer Gradle versions because they have changed.

Gradle 6:
```
java.lang.NoSuchMethodError: org.gradle.api.reporting.internal.TaskReportContainer.<init>(Ljava/lang/Class;Lorg/gradle/api/Task;)V
        at com.tngtech.jgiven.gradle.internal.JGivenReportsContainerImpl.<init>(JGivenReportsContainerImpl.java:11)
```

Gradle 5.6.3, 5.6.4:
```
java.lang.NoClassDefFoundError: org/gradle/api/internal/ClosureBackedAction
        at com.tngtech.jgiven.gradle.JGivenReportTask.reports(JGivenReportTask.java:65)
```

**Comment by sharedprophet** [comment]
You’re still using gradle internal classes...

**Comment by janschaefer** [comment]
Can you suggest a better implementation?

**Comment by sharedprophet** [comment]
Ugh. After looking more closely... not really. : (
