### ISSUE TITLE
Getting error when running on Java 12

### ISSUE THREAD

**Issue by mivr83** [TNG/JGiven#448]
When running on Java 8 tests run as expected but when i try to execute them on Java 12 then i get this exception: 

java.lang.RuntimeException: Error while trying to create an instance of class class *****.steps.given.GivenSteps
	at com.tngtech.jgiven.impl.DefaultStageCreator.createStage(DefaultStageCreator.java:25)
	at com.tngtech.jgiven.impl.ScenarioExecutor.addStage(ScenarioExecutor.java:224)
	at com.tngtech.jgiven.impl.Scenario.initialize(Scenario.java:98)
	at com.tngtech.jgiven.impl.ScenarioBase.performInitialization(ScenarioBase.java:91)
	at com.tngtech.jgiven.impl.ScenarioBase.startScenario(ScenarioBase.java:74)
	at com.tngtech.jgiven.junit.JGivenMethodRule.starting(JGivenMethodRule.java:109)
	at com.tngtech.jgiven.junit.JGivenMethodRule$1.evaluate(JGivenMethodRule.java:71)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.tngtech.java.junit.dataprovider.DataProviderRunner$1.evaluate(DataProviderRunner.java:170)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Cannot define nest member class java.lang.reflect.AccessibleObject$Cache + within different package then class net.bytebuddy.mirror.AccessibleObject
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:411)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:236)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:112)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:232)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:143)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5662)
	at com.tngtech.jgiven.impl.ByteBuddyStageClassCreator.createStageClass(ByteBuddyStageClassCreator.java:57)
	at com.tngtech.jgiven.impl.CachingStageClassCreator.getCachedClass(CachingStageClassCreator.java:29)
	at com.tngtech.jgiven.impl.CachingStageClassCreator.createStageClass(CachingStageClassCreator.java:22)
	at com.tngtech.jgiven.impl.DefaultStageCreator.createStage(DefaultStageCreator.java:18)
	... 30 more

Any idea  how to fix this?

**Comment by janschaefer** [comment]
Could you try version 1.0.0-RC4?

**Comment by mivr83** [comment]
So i have tryied proposed 1.0.0-RC4 but result is practically same with slightly diff stacktrace (exact java version im testing it on is 12.0.1):

java.lang.RuntimeException: Error while trying to create an instance of class class ****.steps.given.GivenSteps
	at com.tngtech.jgiven.impl.DefaultStageCreator.createStage(DefaultStageCreator.java:25)
	at com.tngtech.jgiven.impl.ScenarioExecutor.addStage(ScenarioExecutor.java:230)
	at com.tngtech.jgiven.impl.Scenario.initialize(Scenario.java:98)
	at com.tngtech.jgiven.impl.ScenarioBase.performInitialization(ScenarioBase.java:91)
	at com.tngtech.jgiven.impl.ScenarioBase.startScenario(ScenarioBase.java:74)
	at com.tngtech.jgiven.junit.JGivenMethodRule.starting(JGivenMethodRule.java:109)
	at com.tngtech.jgiven.junit.JGivenMethodRule$1.evaluate(JGivenMethodRule.java:71)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.tngtech.java.junit.dataprovider.DataProviderRunner$1.evaluate(DataProviderRunner.java:170)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.IllegalArgumentException: Could not create type
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:154)
	at com.tngtech.jgiven.impl.CachingStageClassCreator.createStageClass(CachingStageClassCreator.java:20)
	at com.tngtech.jgiven.impl.DefaultStageCreator.createStage(DefaultStageCreator.java:18)
	... 30 more
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Cannot define nest member class java.lang.reflect.AccessibleObject$Cache + within different package then class net.bytebuddy.mirror.AccessibleObject
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:411)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:236)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:112)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:232)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:143)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5662)
	at com.tngtech.jgiven.impl.ByteBuddyStageClassCreator.createStageClass(ByteBuddyStageClassCreator.java:57)
	at com.tngtech.jgiven.impl.CachingStageClassCreator.lambda$createStageClass$7(CachingStageClassCreator.java:21)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
	... 32 more

**Comment by janschaefer** [comment]
Ok. This is strange. Could it be that you have an older version of Bytebuddy in your classpath from another dependency? Because JGiven is tested against Java 12.

**Comment by mivr83** [comment]
Your suggestion was correct, in project was older version of mockito (mockito-all) and this was cause of problem. Now it all goes as supposed. 

Thx for help
